#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged

# If everything passes... Now we can commit
echo 'Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

pnpm turbo build lint ||
(
    echo 'Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ You win this time... I am committing this now.'